spring.application.name=customer-service
server.port=8081



#DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=266761522
spring.datasource.driver-class-name=org.postgresql.Driver


#Jpa Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.cloud.discovery.enabled=false
spring.cloud.config.enabled=false